version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: bull_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
